// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/fedratlas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FeatureChangeRequest represents a feature change event
type FeatureChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeatureId     int64                  `protobuf:"varint,1,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	ActivityType  string                 `protobuf:"bytes,2,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"` // "Create", "Update", "Delete"
	FeatureData   []byte                 `protobuf:"bytes,3,opt,name=feature_data,json=featureData,proto3" json:"feature_data,omitempty"`    // GeoJSON data
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	CollectionId  string                 `protobuf:"bytes,5,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // "roads", "pois", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureChangeRequest) Reset() {
	*x = FeatureChangeRequest{}
	mi := &file_proto_fedratlas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureChangeRequest) ProtoMessage() {}

func (x *FeatureChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fedratlas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureChangeRequest.ProtoReflect.Descriptor instead.
func (*FeatureChangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_fedratlas_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureChangeRequest) GetFeatureId() int64 {
	if x != nil {
		return x.FeatureId
	}
	return 0
}

func (x *FeatureChangeRequest) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *FeatureChangeRequest) GetFeatureData() []byte {
	if x != nil {
		return x.FeatureData
	}
	return nil
}

func (x *FeatureChangeRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FeatureChangeRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

type FeatureChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureChangeResponse) Reset() {
	*x = FeatureChangeResponse{}
	mi := &file_proto_fedratlas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureChangeResponse) ProtoMessage() {}

func (x *FeatureChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fedratlas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureChangeResponse.ProtoReflect.Descriptor instead.
func (*FeatureChangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_fedratlas_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureChangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FeatureChangeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Peer management
type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	TrustScore    float64                `protobuf:"fixed64,3,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	EndpointUrl   string                 `protobuf:"bytes,4,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	LastSeen      int64                  `protobuf:"varint,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_proto_fedratlas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fedratlas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_proto_fedratlas_proto_rawDescGZIP(), []int{2}
}

func (x *Peer) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Peer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Peer) GetTrustScore() float64 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

func (x *Peer) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

func (x *Peer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Peer) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *Peer) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type AddPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *Peer                  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPeerRequest) Reset() {
	*x = AddPeerRequest{}
	mi := &file_proto_fedratlas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerRequest) ProtoMessage() {}

func (x *AddPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fedratlas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerRequest.ProtoReflect.Descriptor instead.
func (*AddPeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_fedratlas_proto_rawDescGZIP(), []int{3}
}

func (x *AddPeerRequest) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type AddPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPeerResponse) Reset() {
	*x = AddPeerResponse{}
	mi := &file_proto_fedratlas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerResponse) ProtoMessage() {}

func (x *AddPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fedratlas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerResponse.ProtoReflect.Descriptor instead.
func (*AddPeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_fedratlas_proto_rawDescGZIP(), []int{4}
}

func (x *AddPeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddPeerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersRequest) Reset() {
	*x = GetPeersRequest{}
	mi := &file_proto_fedratlas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersRequest) ProtoMessage() {}

func (x *GetPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fedratlas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersRequest.ProtoReflect.Descriptor instead.
func (*GetPeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_fedratlas_proto_rawDescGZIP(), []int{5}
}

type GetPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersResponse) Reset() {
	*x = GetPeersResponse{}
	mi := &file_proto_fedratlas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResponse) ProtoMessage() {}

func (x *GetPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fedratlas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResponse.ProtoReflect.Descriptor instead.
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return file_proto_fedratlas_proto_rawDescGZIP(), []int{6}
}

func (x *GetPeersResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type GetServerIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerIDRequest) Reset() {
	*x = GetServerIDRequest{}
	mi := &file_proto_fedratlas_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerIDRequest) ProtoMessage() {}

func (x *GetServerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fedratlas_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerIDRequest.ProtoReflect.Descriptor instead.
func (*GetServerIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_fedratlas_proto_rawDescGZIP(), []int{7}
}

type GetServerIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerIDResponse) Reset() {
	*x = GetServerIDResponse{}
	mi := &file_proto_fedratlas_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerIDResponse) ProtoMessage() {}

func (x *GetServerIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fedratlas_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerIDResponse.ProtoReflect.Descriptor instead.
func (*GetServerIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_fedratlas_proto_rawDescGZIP(), []int{8}
}

func (x *GetServerIDResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// Manifest
type Manifest struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	ProtocolVersion string                   `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ServerId        string                   `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Status          string                   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	PublicKey       string                   `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoints       *Manifest_EndpointConfig `protobuf:"bytes,5,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	Datasets        []*Manifest_DatasetInfo  `protobuf:"bytes,6,rep,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_proto_fedratlas_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fedratlas_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_proto_fedratlas_proto_rawDescGZIP(), []int{9}
}

func (x *Manifest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Manifest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Manifest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Manifest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Manifest) GetEndpoints() *Manifest_EndpointConfig {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Manifest) GetDatasets() []*Manifest_DatasetInfo {
	if x != nil {
		return x.Datasets
	}
	return nil
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_proto_fedratlas_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fedratlas_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_proto_fedratlas_proto_rawDescGZIP(), []int{10}
}

type Manifest_EndpointConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InboxUrl      string                 `protobuf:"bytes,1,opt,name=inbox_url,json=inboxUrl,proto3" json:"inbox_url,omitempty"`
	OutboxUrl     string                 `protobuf:"bytes,2,opt,name=outbox_url,json=outboxUrl,proto3" json:"outbox_url,omitempty"`
	ManifestUrl   string                 `protobuf:"bytes,3,opt,name=manifest_url,json=manifestUrl,proto3" json:"manifest_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest_EndpointConfig) Reset() {
	*x = Manifest_EndpointConfig{}
	mi := &file_proto_fedratlas_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest_EndpointConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest_EndpointConfig) ProtoMessage() {}

func (x *Manifest_EndpointConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fedratlas_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest_EndpointConfig.ProtoReflect.Descriptor instead.
func (*Manifest_EndpointConfig) Descriptor() ([]byte, []int) {
	return file_proto_fedratlas_proto_rawDescGZIP(), []int{9, 0}
}

func (x *Manifest_EndpointConfig) GetInboxUrl() string {
	if x != nil {
		return x.InboxUrl
	}
	return ""
}

func (x *Manifest_EndpointConfig) GetOutboxUrl() string {
	if x != nil {
		return x.OutboxUrl
	}
	return ""
}

func (x *Manifest_EndpointConfig) GetManifestUrl() string {
	if x != nil {
		return x.ManifestUrl
	}
	return ""
}

type Manifest_DatasetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FeatureCount  int64                  `protobuf:"varint,4,opt,name=feature_count,json=featureCount,proto3" json:"feature_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest_DatasetInfo) Reset() {
	*x = Manifest_DatasetInfo{}
	mi := &file_proto_fedratlas_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest_DatasetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest_DatasetInfo) ProtoMessage() {}

func (x *Manifest_DatasetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fedratlas_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest_DatasetInfo.ProtoReflect.Descriptor instead.
func (*Manifest_DatasetInfo) Descriptor() ([]byte, []int) {
	return file_proto_fedratlas_proto_rawDescGZIP(), []int{9, 1}
}

func (x *Manifest_DatasetInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manifest_DatasetInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest_DatasetInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manifest_DatasetInfo) GetFeatureCount() int64 {
	if x != nil {
		return x.FeatureCount
	}
	return 0
}

var File_proto_fedratlas_proto protoreflect.FileDescriptor

const file_proto_fedratlas_proto_rawDesc = "" +
	"\n" +
	"\x15proto/fedratlas.proto\x12\tfedratlas\"\xbc\x01\n" +
	"\x14FeatureChangeRequest\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x01 \x01(\x03R\tfeatureId\x12#\n" +
	"\ractivity_type\x18\x02 \x01(\tR\factivityType\x12!\n" +
	"\ffeature_data\x18\x03 \x01(\fR\vfeatureData\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12#\n" +
	"\rcollection_id\x18\x05 \x01(\tR\fcollectionId\"G\n" +
	"\x15FeatureChangeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xda\x01\n" +
	"\x04Peer\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vtrust_score\x18\x03 \x01(\x01R\n" +
	"trustScore\x12!\n" +
	"\fendpoint_url\x18\x04 \x01(\tR\vendpointUrl\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\x03R\blastSeen\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"5\n" +
	"\x0eAddPeerRequest\x12#\n" +
	"\x04peer\x18\x01 \x01(\v2\x0f.fedratlas.PeerR\x04peer\"A\n" +
	"\x0fAddPeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x11\n" +
	"\x0fGetPeersRequest\"9\n" +
	"\x10GetPeersResponse\x12%\n" +
	"\x05peers\x18\x01 \x03(\v2\x0f.fedratlas.PeerR\x05peers\"\x14\n" +
	"\x12GetServerIDRequest\"2\n" +
	"\x13GetServerIDResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\xf3\x03\n" +
	"\bManifest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12@\n" +
	"\tendpoints\x18\x05 \x01(\v2\".fedratlas.Manifest.EndpointConfigR\tendpoints\x12;\n" +
	"\bdatasets\x18\x06 \x03(\v2\x1f.fedratlas.Manifest.DatasetInfoR\bdatasets\x1ao\n" +
	"\x0eEndpointConfig\x12\x1b\n" +
	"\tinbox_url\x18\x01 \x01(\tR\binboxUrl\x12\x1d\n" +
	"\n" +
	"outbox_url\x18\x02 \x01(\tR\toutboxUrl\x12!\n" +
	"\fmanifest_url\x18\x03 \x01(\tR\vmanifestUrl\x1ax\n" +
	"\vDatasetInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rfeature_count\x18\x04 \x01(\x03R\ffeatureCount\"\x14\n" +
	"\x12GetManifestRequest2\x80\x03\n" +
	"\x10FedratlasService\x12T\n" +
	"\x0fOnFeatureChange\x12\x1f.fedratlas.FeatureChangeRequest\x1a .fedratlas.FeatureChangeResponse\x12@\n" +
	"\aAddPeer\x12\x19.fedratlas.AddPeerRequest\x1a\x1a.fedratlas.AddPeerResponse\x12C\n" +
	"\bGetPeers\x12\x1a.fedratlas.GetPeersRequest\x1a\x1b.fedratlas.GetPeersResponse\x12L\n" +
	"\vGetServerID\x12\x1d.fedratlas.GetServerIDRequest\x1a\x1e.fedratlas.GetServerIDResponse\x12A\n" +
	"\vGetManifest\x12\x1d.fedratlas.GetManifestRequest\x1a\x13.fedratlas.ManifestB(Z&github.com/fedratlas/sync-engine/protob\x06proto3"

var (
	file_proto_fedratlas_proto_rawDescOnce sync.Once
	file_proto_fedratlas_proto_rawDescData []byte
)

func file_proto_fedratlas_proto_rawDescGZIP() []byte {
	file_proto_fedratlas_proto_rawDescOnce.Do(func() {
		file_proto_fedratlas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fedratlas_proto_rawDesc), len(file_proto_fedratlas_proto_rawDesc)))
	})
	return file_proto_fedratlas_proto_rawDescData
}

var file_proto_fedratlas_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_fedratlas_proto_goTypes = []any{
	(*FeatureChangeRequest)(nil),    // 0: fedratlas.FeatureChangeRequest
	(*FeatureChangeResponse)(nil),   // 1: fedratlas.FeatureChangeResponse
	(*Peer)(nil),                    // 2: fedratlas.Peer
	(*AddPeerRequest)(nil),          // 3: fedratlas.AddPeerRequest
	(*AddPeerResponse)(nil),         // 4: fedratlas.AddPeerResponse
	(*GetPeersRequest)(nil),         // 5: fedratlas.GetPeersRequest
	(*GetPeersResponse)(nil),        // 6: fedratlas.GetPeersResponse
	(*GetServerIDRequest)(nil),      // 7: fedratlas.GetServerIDRequest
	(*GetServerIDResponse)(nil),     // 8: fedratlas.GetServerIDResponse
	(*Manifest)(nil),                // 9: fedratlas.Manifest
	(*GetManifestRequest)(nil),      // 10: fedratlas.GetManifestRequest
	(*Manifest_EndpointConfig)(nil), // 11: fedratlas.Manifest.EndpointConfig
	(*Manifest_DatasetInfo)(nil),    // 12: fedratlas.Manifest.DatasetInfo
}
var file_proto_fedratlas_proto_depIdxs = []int32{
	2,  // 0: fedratlas.AddPeerRequest.peer:type_name -> fedratlas.Peer
	2,  // 1: fedratlas.GetPeersResponse.peers:type_name -> fedratlas.Peer
	11, // 2: fedratlas.Manifest.endpoints:type_name -> fedratlas.Manifest.EndpointConfig
	12, // 3: fedratlas.Manifest.datasets:type_name -> fedratlas.Manifest.DatasetInfo
	0,  // 4: fedratlas.FedratlasService.OnFeatureChange:input_type -> fedratlas.FeatureChangeRequest
	3,  // 5: fedratlas.FedratlasService.AddPeer:input_type -> fedratlas.AddPeerRequest
	5,  // 6: fedratlas.FedratlasService.GetPeers:input_type -> fedratlas.GetPeersRequest
	7,  // 7: fedratlas.FedratlasService.GetServerID:input_type -> fedratlas.GetServerIDRequest
	10, // 8: fedratlas.FedratlasService.GetManifest:input_type -> fedratlas.GetManifestRequest
	1,  // 9: fedratlas.FedratlasService.OnFeatureChange:output_type -> fedratlas.FeatureChangeResponse
	4,  // 10: fedratlas.FedratlasService.AddPeer:output_type -> fedratlas.AddPeerResponse
	6,  // 11: fedratlas.FedratlasService.GetPeers:output_type -> fedratlas.GetPeersResponse
	8,  // 12: fedratlas.FedratlasService.GetServerID:output_type -> fedratlas.GetServerIDResponse
	9,  // 13: fedratlas.FedratlasService.GetManifest:output_type -> fedratlas.Manifest
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_fedratlas_proto_init() }
func file_proto_fedratlas_proto_init() {
	if File_proto_fedratlas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fedratlas_proto_rawDesc), len(file_proto_fedratlas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fedratlas_proto_goTypes,
		DependencyIndexes: file_proto_fedratlas_proto_depIdxs,
		MessageInfos:      file_proto_fedratlas_proto_msgTypes,
	}.Build()
	File_proto_fedratlas_proto = out.File
	file_proto_fedratlas_proto_goTypes = nil
	file_proto_fedratlas_proto_depIdxs = nil
}
