// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/fedratlas.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FedratlasService_OnFeatureChange_FullMethodName = "/fedratlas.FedratlasService/OnFeatureChange"
	FedratlasService_AddPeer_FullMethodName         = "/fedratlas.FedratlasService/AddPeer"
	FedratlasService_GetPeers_FullMethodName        = "/fedratlas.FedratlasService/GetPeers"
	FedratlasService_GetServerID_FullMethodName     = "/fedratlas.FedratlasService/GetServerID"
	FedratlasService_GetManifest_FullMethodName     = "/fedratlas.FedratlasService/GetManifest"
)

// FedratlasServiceClient is the client API for FedratlasService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FedratlasService provides federation synchronization for OGC API maps
type FedratlasServiceClient interface {
	// OnFeatureChange is called when a feature is created, updated, or deleted
	OnFeatureChange(ctx context.Context, in *FeatureChangeRequest, opts ...grpc.CallOption) (*FeatureChangeResponse, error)
	// AddPeer adds a new peer server to the federation
	AddPeer(ctx context.Context, in *AddPeerRequest, opts ...grpc.CallOption) (*AddPeerResponse, error)
	// GetPeers returns all active peers
	GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error)
	// GetServerID returns this server's ID
	GetServerID(ctx context.Context, in *GetServerIDRequest, opts ...grpc.CallOption) (*GetServerIDResponse, error)
	// GetManifest returns the server manifest
	GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*Manifest, error)
}

type fedratlasServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFedratlasServiceClient(cc grpc.ClientConnInterface) FedratlasServiceClient {
	return &fedratlasServiceClient{cc}
}

func (c *fedratlasServiceClient) OnFeatureChange(ctx context.Context, in *FeatureChangeRequest, opts ...grpc.CallOption) (*FeatureChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureChangeResponse)
	err := c.cc.Invoke(ctx, FedratlasService_OnFeatureChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fedratlasServiceClient) AddPeer(ctx context.Context, in *AddPeerRequest, opts ...grpc.CallOption) (*AddPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPeerResponse)
	err := c.cc.Invoke(ctx, FedratlasService_AddPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fedratlasServiceClient) GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeersResponse)
	err := c.cc.Invoke(ctx, FedratlasService_GetPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fedratlasServiceClient) GetServerID(ctx context.Context, in *GetServerIDRequest, opts ...grpc.CallOption) (*GetServerIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerIDResponse)
	err := c.cc.Invoke(ctx, FedratlasService_GetServerID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fedratlasServiceClient) GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*Manifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Manifest)
	err := c.cc.Invoke(ctx, FedratlasService_GetManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FedratlasServiceServer is the server API for FedratlasService service.
// All implementations must embed UnimplementedFedratlasServiceServer
// for forward compatibility.
//
// FedratlasService provides federation synchronization for OGC API maps
type FedratlasServiceServer interface {
	// OnFeatureChange is called when a feature is created, updated, or deleted
	OnFeatureChange(context.Context, *FeatureChangeRequest) (*FeatureChangeResponse, error)
	// AddPeer adds a new peer server to the federation
	AddPeer(context.Context, *AddPeerRequest) (*AddPeerResponse, error)
	// GetPeers returns all active peers
	GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error)
	// GetServerID returns this server's ID
	GetServerID(context.Context, *GetServerIDRequest) (*GetServerIDResponse, error)
	// GetManifest returns the server manifest
	GetManifest(context.Context, *GetManifestRequest) (*Manifest, error)
	mustEmbedUnimplementedFedratlasServiceServer()
}

// UnimplementedFedratlasServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFedratlasServiceServer struct{}

func (UnimplementedFedratlasServiceServer) OnFeatureChange(context.Context, *FeatureChangeRequest) (*FeatureChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnFeatureChange not implemented")
}
func (UnimplementedFedratlasServiceServer) AddPeer(context.Context, *AddPeerRequest) (*AddPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPeer not implemented")
}
func (UnimplementedFedratlasServiceServer) GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPeers not implemented")
}
func (UnimplementedFedratlasServiceServer) GetServerID(context.Context, *GetServerIDRequest) (*GetServerIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerID not implemented")
}
func (UnimplementedFedratlasServiceServer) GetManifest(context.Context, *GetManifestRequest) (*Manifest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedFedratlasServiceServer) mustEmbedUnimplementedFedratlasServiceServer() {}
func (UnimplementedFedratlasServiceServer) testEmbeddedByValue()                          {}

// UnsafeFedratlasServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FedratlasServiceServer will
// result in compilation errors.
type UnsafeFedratlasServiceServer interface {
	mustEmbedUnimplementedFedratlasServiceServer()
}

func RegisterFedratlasServiceServer(s grpc.ServiceRegistrar, srv FedratlasServiceServer) {
	// If the following call panics, it indicates UnimplementedFedratlasServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FedratlasService_ServiceDesc, srv)
}

func _FedratlasService_OnFeatureChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FedratlasServiceServer).OnFeatureChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FedratlasService_OnFeatureChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FedratlasServiceServer).OnFeatureChange(ctx, req.(*FeatureChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FedratlasService_AddPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FedratlasServiceServer).AddPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FedratlasService_AddPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FedratlasServiceServer).AddPeer(ctx, req.(*AddPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FedratlasService_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FedratlasServiceServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FedratlasService_GetPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FedratlasServiceServer).GetPeers(ctx, req.(*GetPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FedratlasService_GetServerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FedratlasServiceServer).GetServerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FedratlasService_GetServerID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FedratlasServiceServer).GetServerID(ctx, req.(*GetServerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FedratlasService_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FedratlasServiceServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FedratlasService_GetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FedratlasServiceServer).GetManifest(ctx, req.(*GetManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FedratlasService_ServiceDesc is the grpc.ServiceDesc for FedratlasService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FedratlasService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fedratlas.FedratlasService",
	HandlerType: (*FedratlasServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnFeatureChange",
			Handler:    _FedratlasService_OnFeatureChange_Handler,
		},
		{
			MethodName: "AddPeer",
			Handler:    _FedratlasService_AddPeer_Handler,
		},
		{
			MethodName: "GetPeers",
			Handler:    _FedratlasService_GetPeers_Handler,
		},
		{
			MethodName: "GetServerID",
			Handler:    _FedratlasService_GetServerID_Handler,
		},
		{
			MethodName: "GetManifest",
			Handler:    _FedratlasService_GetManifest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fedratlas.proto",
}
